import type { Metadata } from "next";

import "./index.css";
import { Container, HStack, Stack, Wrap } from "styled-system/jsx";
import { Text } from "components/ui/text";
import { Link } from "components/ui/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Stack minH="screen">
          <Container flex={1} display="flex">
            {children}
          </Container>
        </Stack>
      </body>
    </html>
  );
}
