import type { Metadata } from 'next';
import { Container, Stack } from 'styled-system/jsx';

import './index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Stack minH="screen">
          <Container display="flex" flex={1}>
            {children}
          </Container>
        </Stack>
      </body>
    </html>
  );
}
